version: '3.7'

services:
  app:
    volumes:
      - static_data:/vol/web
    image: filip231/projectmyapi

  proxy:
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
    image: filip231/projectproxy

volumes:
  static_data:
