# Generated by Django 3.1.7 on 2021-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
