# Generated by Django 3.1.7 on 2021-03-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210311_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='top_speed',
            new_name='model',
        ),
    ]
