# Generated by Django 3.1.7 on 2021-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rating_rates_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('avaiable_models', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
