# Generated by Django 3.1.7 on 2021-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_rating_avg_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='avaiable_models',
            new_name='available_models',
        ),
    ]
