# Generated by Django 3.0.13 on 2021-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210317_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
