# Generated by Django 3.0.13 on 2021-03-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rates_number',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rates_sum',
        ),
    ]
