name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd deploy/
            sudo rm -rf NG-CarApp/
            git clone git@github.com:Filip-231/NG-CarApp.git
            cd NG-CarApp/
            sudo docker-compose down
            y | sudo docker system prune --volumes
            sudo docker-compose build
            sudo docker-compose up -d
          host: ${{ secrets.STAGING_HOST }}
          user: ubuntu
          key: ${{ secrets.STAGING_KEY}}