name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -la
            whoami
            ls -a
            cd deploy/
            git clone git@github.com:Filip-231/NG-CarApp.git
            git fetch --all
            ls -la
            sudo docker-compose build
            sudo docker-compose up
          host: ${{ secrets.STAGING_HOST }}
          user: ubuntu
          key: ${{ secrets.STAGING_KEY}}