name: Deploy Staging
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd deploy/
            export ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            sudo rm -rf NG-CarApp/
            git clone git@github.com:Filip-231/NG-CarApp.git
            cd NG-CarApp/
            sudo docker-compose down
            yes | sudo docker system prune --volumes
            sudo docker-compose build
            sudo docker-compose up -d
          host: ${{ secrets.STAGING_HOST }}
          user: ubuntu
          key: ${{ secrets.STAGING_KEY}}