name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -la
            whoami
            cd /tmp
            ls -a
            sudo apt install curl
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo docker–compose --version
            sudo docker-compose build
            sudo docker-compose up
          host: ${{ secrets.STAGING_HOST }}
          user: ubuntu
          key: ${{ secrets.STAGING_KEY}}